### ISSUE TITLE
Support for 'expand' operator

### ISSUE THREAD

**Issue by jasondicker** [relair/odata-data-source#5]
Thanks for the great library! Unfortunately there's no way to expand properties. Please add this functionality. Thanks,

**Comment by jsmuise** [comment]
I have the same requirement I would like to display the "name" property of the related entity instead of the id that links the two entities.  With the current implementation I cannot pass the following to the constructor "http://someapi.com/api/myresource?$expand=myrelatedresource" as the class will then append "?$top=5&$count=true" (based on my configuration) to the end of the URI making it invalid.

**Comment by relair** [comment]
I have released version 9.3.0 which adds support for using expand. Use expandedFields property with either object or array of strings.

**Comment by igortelheiro** [comment]
Thanks @relair, I´ve recently started using your library and Expand support is a huge improve I was needing so bad. Great job!
